### ISSUE TITLE
transient segfault observed

### ISSUE THREAD

**Issue by noahdesu** [senior7515/smf#185] opened 2017-12-15 21:09 UTC
https://travis-ci.org/noahdesu/smf/jobs/315704720#L2667

**Comment by senior7515** [comment] 2017-12-16 14:04
I've seen this on Travis before. Will look at it in detail.  

Last time was that Travis ran out of disk space. 

Thanks for reporting

**Comment by senior7515** [comment] 2017-12-17 00:39
looked at the code. 

```cpp
seastar::future<> wal_partition_manager::open() {
  LOG_DEBUG("Opening partition manager with: opts={}, topic={}, partition={}",
            opts, topic, partition);
  seastar::sstring dir = topic + "." + seastar::to_sstring(partition);
  return file_exists(dir)
    .then([dir](bool exists) {
      if (exists) { return seastar::make_ready_future<>(); }
      return seastar::make_directory(dir).then_wrapped(
        [](auto _) { return seastar::make_ready_future<>(); });
    })
    .then_wrapped([this](auto _) { return this->do_open(); });
}


```

have u managed to repro locally?

**Comment by senior7515** [comment] 2017-12-17 01:03
hmm come to think of it, you could create the dir multiple times, but that seems OK w/ me. in fact looking at the code, i `then_wrapped` it explicitly which means I'm explicitly ignoring this 'possible' failure. 

alternatively - and correctly, i should probably serialize this one step to core 0 since all the cores will use this as the begining stage. 

all the other dir making funcs are correct and have a lcore-postfix which ensures that only that one handling thread is opening or making files / directories.

**Comment by noahdesu** [comment] 2017-12-17 01:08
i haven't seen it locally, and even on travis it only happened once out of a few runs. but that stack trace is totally obnoxious. have you figured out how to get symbols in the seastar back traces? i seem to recall not having them even when i was using the debug build.

**Comment by senior7515** [comment] 2017-12-17 01:37
yeah, you have to use seastar-addr2line program in the $SEASTAR/scripts/ folder. 

i thought I needed the binary, i see it w/ gcc 4.8 is when it occurred so I'll need to figure it out when this happens with compilers not in my sys. 

how do you do it for zlog, do you just run docker the normal `.ci/local.sh` and then docker run -it bash `hash<>` ?

**Comment by noahdesu** [comment] 2017-12-17 03:32
i'm a little confused by your question. are you asking how to reproduce just one of the build configurations on travis? what is hash<>?

**Comment by senior7515** [comment] 2017-12-17 06:38
You wouldn't understand because I wrote unintelligible things, sorry. 

What I meant to ask is: how do you debug crashes in zlog for non native builds (builds that are not your development environment). I.e.: are you using docker to recreate the failures and then debug them also using docker. Or are you using docker for cross builds but virtual machine to debug.... Was just wondering

**Comment by senior7515** [comment] 2017-12-17 16:38
I used the addr2line w/ a debug build of master on my computer and it's hard to tell exactly without having the same environment. 

```
seastar::future<seastar::lw_shared_ptr<smf::wal_partition_manager> >::~future() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:800                                                                                                                        
 (inlined by) _ZZN7seastar6futureIJNS_13lw_shared_ptrIN3smf21wal_partition_managerEEEEE12then_wrappedINS5_12finally_bodyIZNS2_16wal_impl_details22partition_manager_list11get_managerEjEUlvE0_Lb0EEES5_EET0_OT_ENUlSE_E_clINS_12future_stateIJS4_EEEEEDaSE_ at /home/agallego/workspace/sm
f/build_debug/../meta/tmp/seastar/core/future.hh:946                                                                                                                                                                                                                                      
_ZN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZNS_7shardedIN3smf21write_ahead_log_proxyEE5startIJNS5_8wal_optsEEEES2_DpOT_EUlS2_E0_S2_EET0_OT_EUlSG_E_JEEC2EOSH_ at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:394                             
_ZN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZNS_7shardedIN3smf21write_ahead_log_proxyEE5startIJNS5_8wal_optsEEEES2_DpOT_EUlS2_E0_S2_EET0_OT_EUlSG_E_JEEC2EOSH_ at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:394                             
std::move_iterator<std::pair<fmt::BasicStringRef<char>, fmt::internal::Arg>*>::operator*() const at /usr/include/c++/7/bits/stl_iterator.h:1050                                                                                                                                           
seastar::future<>::state() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:721                                                                                                                                                                             
 (inlined by) seastar::future<>::failed() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:867                                                                                                                                                              
 (inlined by) seastar::future<>::~future() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:799                                                                                                                                                             
 (inlined by) seastar::future<> seastar::future<>::then_wrapped<seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}::operator()(uns
igned int) const::{lambda()#1}>::process()::{lambda(auto:1&&)#1}, seastar::future<> >(seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned i
nt)#1}::operator()(unsigned int) const::{lambda()#1}>)::{lambda(seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}::operator()(uns
igned int) const::{lambda()#1}>)#1}::operator()<seastar::future_state<> >(auto, seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}
::operator()(unsigned int) const::{lambda()#1}>) at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:946                                                                                                                                                       
seastar::future<>::state() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:721                                                                                                                                                                             
 (inlined by) seastar::future<>::failed() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:867                                                                                                                                                              
 (inlined by) seastar::future<>::~future() at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:799                                                                                                                                                             
 (inlined by) seastar::future<> seastar::future<>::then_wrapped<seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}::operator()(uns
igned int) const::{lambda()#1}>::process()::{lambda(auto:1&&)#1}, seastar::future<> >(seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned i
nt)#1}::operator()(unsigned int) const::{lambda()#1}>)::{lambda(seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}::operator()(uns
igned int) const::{lambda()#1}>)#1}::operator()<seastar::future_state<> >(auto, seastar::smp_message_queue::async_work_item<seastar::future<> seastar::sharded<smf::write_ahead_log_proxy>::invoke_on_all<>(seastar::future<> (smf::write_ahead_log_proxy::*)())::{lambda(unsigned int)#1}
::operator()(unsigned int) const::{lambda()#1}>) at /home/agallego/workspace/smf/build_debug/../meta/tmp/seastar/core/future.hh:946                                                                                                                                                       
?? ??:0                                                                                                                                                                                                                                                                                   
?? ??:0                                                                                                                                                                                                                                                                                   
?? ??:0                                                                                                                                                                                                                                                                                   
?? ??:0                                                                                                                                                                                                                                                                                   
?? ??:0 

```


I'm going to solve the contention issue as well. 

The strategy is: 

1) Abort if root-directory-to-place-the-write-ahead-log is not present. 
2) Each lcore makes it's own working-dir like this 

```
$ROOT/
 .........../lcore0/wal_0:0...log
.........../lcore1/wal_...
```

thoughts ?

**Comment by senior7515** [comment] 2017-12-17 16:51
Oh, so we alreadey do this. 

```
  seastar::sstring dir = topic + "." + seastar::to_sstring(partition);

```
we just had to serialize the creating of the root directory. I wouldn't be surprised if this was a filesystem bug. 

Thanks for reporting. 

Let me know if you have thoughts on the patch.

**Comment by noahdesu** [comment] 2017-12-17 17:20
I always try to reproduce the bug locally in the same docker execution environment in which the bug occurred remotely in travis. Or in my normal dev environment if the bug looks simple enough. When you reproduce it locally in the docker container, you can jump in that get a gdb session open.

In zlog I invoke addr2line from a segfault handler (https://github.com/cruzdb/zlog/blob/4b77b43f776a47aab796ada48b4f9640498e8c1d/src/port/stack_trace.cc#L58) to get the symbols to print out correctly. That makes life way easier for getting an idea of what happened remotely.

For seastar / smf debugging I guess we'll need to choose between a few options

1) it looks like we might just be able to pipe the output of stderr for test runs through seastar-addr2line since it just echos lines that don't contain symbols (https://github.com/scylladb/seastar/blob/e60afd24a1f120dab50959748fe58a8791ae4e0d/scripts/seastar-addr2line#L51). if that works, its probably the easiest solution.

2) could dump a symbol table on vm startup

3) on failure we could upload the symbol table or a core image to some where temporary, like an s3 object or something. there are a few options.

**Comment by noahdesu** [comment] 2017-12-17 17:22
the reasoning behind that patch, for delegating mkdir to core0, makes total sense. i'm still a total seastar newbie, but at a glance it seems good.

**Comment by senior7515** [comment] 2017-12-17 23:09
I haven't been able to reproduce the bug yet. But I found a couple other enhancements on the write ahead log. 

I'veen working on porting a modified version of the Kernel's clock-pro.

I'll submit patches in a couple of PR.

Anyway, the race to create all directories should be fixed correctly soon. 

Thanks for reporting.

**Comment by senior7515** [comment] 2017-12-18 04:49
@noahdesu I just merged the code that correctly handles ownership of creating directories.

**Comment by senior7515** [comment] 2017-12-18 04:50
I also really like your addr2line, maybe we can add it to the test suite like you said.

**Comment by senior7515** [comment] 2017-12-20 06:06
Given that the filesystem API has a new flow, I'm going to close this ticket. 

Let's reopen in case it happens again.

**Closed by senior7515** 2017-12-20 06:06 UTC
Labels: bug
