### ISSUE TITLE
Docker test image

### ISSUE THREAD

**Issue by crackcomm** [senior7515/smf#217] opened 2018-03-01 22:08 UTC
Maybe we could build and deploy an image in CI with entire built smf but mainly

1. `demo_apps` - client and server for testing with Go (and later node.js) implementation I am currently working on
2. `smf_gen` - can be useful for someone
3. `load_gen` - not sure what toolchain do you use to graph latencies but it would be useful to have it too :+1: 

This all would be mainly useful for CI testing and this image could be built as the test.

I can submit a pull request just tell me your requirements, OS etc. (Ubuntu 16.04?)

**Comment by senior7515** [comment] 2018-03-01 23:35
this is awesome!!.

Have you looked at the current CI - we actually build inside 9 docker images already, we just don't push them (not actually sure howto yet). 

i wonder if getting a fedora copr repo or a ppa on ubuntu would be a better alternative. 

Do you have any thoughts?

Maybe a 'community maintained' image could be a middle-of-the-road step until we figure out how to push to docker from travis-ci. 

Ideally, we can push to docker with every build in master, for all docker images which include 2 ubuntu and 2 fedora builds.

**Comment by senior7515** [comment] 2018-03-01 23:40
in any case, if you push ubuntu 16.04 we should add it to the documentation as a 'community maintained docker image' 

which can help people get started right away. good idea!

**Comment by crackcomm** [comment] 2018-03-01 23:44
To push to travis, in `ci/one.sh` we have to do

```bash
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
docker push smf/${IMAGE}:latest
```

but password will be visible in logs I think?

**Comment by noahdesu** [comment] 2018-03-01 23:48
@crackcomm are you trying to push up partially build images in order to speed-up compilation?

**Comment by crackcomm** [comment] 2018-03-01 23:53
@noahdesu mostly for integration tests but also for quick development environment.

we already build the images in travis so we can just push them with two lines of code

**Comment by crackcomm** [comment] 2018-03-01 23:56
I think moving `docker login` to `.travis.yml` should solve the issue with password, not 100% sure though.

**Comment by noahdesu** [comment] 2018-03-01 23:58
you can use ci/local.sh for local development and it will cache (or should be caching) the seastar build, so only the smf build is repeated. i only use this for reproducing ci issues, but making this easier to use for local dev setups is totally doable just need someone to give feedback and what it needs.

for speeding up ci, I think the real solution here is to get cmake pushed upstream into seastar. @senior7515 i don't remember what the build times had been, but i recall just a few minutes when all the tests etc... were disabled in the build. The problem with pushing the seastar base images to docker hub (e.g.) is that the debug build of seastar is > 6gb. we could create a custom seastar base image used for integration tests that trimmed this down as far as possible, we'd just have to maintain it.

**Comment by crackcomm** [comment] 2018-03-02 00:04
It could slow down CI severely, I see your point. I [pushed](https://hub.docker.com/r/crackcomm/smf/) my own image for integration tests right now. Uncompressed image was more than 12GB if I remember correctly, it would be nice to have it always latest though.

**Comment by noahdesu** [comment] 2018-03-02 00:21
i agree. maybe we can make a custom release build that is smaller, and also remove all the demo and test apps. that could be pushed to docker hub and kept up to date pretty easily.

**Comment by senior7515** [comment] 2018-03-02 02:13
yeah, total time was something like 8 minutes from scratch which was super fast. I think jessie merged is trying to get the basic patches merged upstream in seastar. 

I guess this problem is likely going away soon once seastar merges cmake.

**Comment by senior7515** [comment] 2018-03-02 02:14
@crackcomm so I'm gna close this issue since a 12G image is def too much. Any issues I might be missing? maybe try @noahdesu 's suggestion of the ./ci/local.sh which should cache things for you?

**Comment by crackcomm** [comment] 2018-03-02 02:19
@senior7515 @noahdesu yes, thanks.

**Closed** 2018-03-02 02:19 UTC
Labels: design, enhancement, good first issue, help wanted
